DROP TABLE IF EXISTS PRODUCT_ENTRY ;

CREATE TABLE PRODUCT_ENTRY
(
    ID              UUID NOT NULL,
    NAME            VARCHAR(15),
    WEIGHT          NUMERIC(10, 2),
    CREATED_DATE    TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_DATE    TIMESTAMP DEFAULT NOW() NOT NULL,
    PRIMARY KEY (ID)
)