version: '2.1'

services:
  psql-db:
    image: postgres:12.14
    container_name: ecommerce-db
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=product
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: cloud-services/gateway
    mem_limit: 512m
    ports:
      - "8443:8443"

  eureka:
    build: cloud-services/discovery-service
    mem_limit: 512m
    ports:
      - '8761:8761'

  product:
    build: app-services/product-service
    mem_limit: '512m'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0
      - SPRING_R2DBC_URL=r2dbc:postgresql://psql-db:5432/product
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  product-1:
    build: app-services/product-service
    mem_limit: '512m'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1
      - SPRING_R2DBC_URL=r2dbc:postgresql://psql-db:5432/product
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  review:
    build: app-services/review-service
    mem_limit: '512m'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0
      - SPRING_R2DBC_URL=r2dbc:postgresql://psql-db:5432/product
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  review-1:
    build: app-services/review-service
    mem_limit: '512m'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1
      - SPRING_R2DBC_URL=r2dbc:postgresql://psql-db:5432/product
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  recommendation:
    build: app-services/recommendation-service
    mem_limit: '512m'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0
      - SPRING_R2DBC_URL=r2dbc:postgresql://psql-db:5432/product
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  recommendation-1:
    build: app-services/recommendation-service
    mem_limit: '512m'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1
      - SPRING_R2DBC_URL=r2dbc:postgresql://psql-db:5432/product
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  product-composite:
    build: app-services/product-composite-service
    mem_limit: 512m
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  rabbitmq:
    image: rabbitmq:3.11.8-management
    mem_limit: 512m
    ports:
      - 5673:5672
      - 15673:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 2s
      retries: 60