version: '2.1'

services:
  psql-db:
    image: postgres:12.14
    container_name: ecommerce-db
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=product
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: cloud-services/gateway
    mem_limit: 512m
    ports:
      - "8443:8443"

  eureka:
    build: cloud-services/discovery-service
    mem_limit: 512m
    ports:
      - '8761:8761'

  product:
    build: app-services/product-service
    mem_limit: '512m'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
      - SPRING_R2DBC_URL=r2dbc:postgresql://psql-db:5432/product
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy
      kafka:
        condition: service_started
  
  product-1:
    build: app-services/product-service
    mem_limit: '512m'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
      - SPRING_R2DBC_URL=r2dbc:postgresql://psql-db:5432/product
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy
      kafka:
        condition: service_started

  review:
    build: app-services/review-service
    mem_limit: '512m'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
      - SPRING_R2DBC_URL=r2dbc:postgresql://psql-db:5432/product
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy
      kafka:
        condition: service_started

  review-1:
    build: app-services/review-service
    mem_limit: '512m'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
      - SPRING_R2DBC_URL=r2dbc:postgresql://psql-db:5432/product
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy
      kafka:
        condition: service_started

  recommendation:
    build: app-services/recommendation-service
    mem_limit: '512m'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_0,kafka
      - SPRING_R2DBC_URL=r2dbc:postgresql://psql-db:5432/product
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy
      kafka:
        condition: service_started

  recommendation-1:
    build: app-services/recommendation-service
    mem_limit: '512m'
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,streaming_instance_1,kafka
      - SPRING_R2DBC_URL=r2dbc:postgresql://psql-db:5432/product
      - SPRING_R2DBC_USERNAME=dev
      - SPRING_R2DBC_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db:
        condition: service_healthy
      kafka:
        condition: service_started

  product-composite:
    build: app-services/product-composite-service
    mem_limit: 512m
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker,streaming_partitioned,kafka
    depends_on:
      kafka:
        condition: service_started
  
  kafka:
    image: confluentinc/cp-kafka:7.3.1
    restart: always
    mem_limit: 1024m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    restart: always
    mem_limit: 512m
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181