DROP TABLE IF EXISTS recommendation_entry ;

CREATE TABLE RECOMMENDATION_ENTRY
(
    ID              UUID NOT NULL,
    PRODUCT_ID      VARCHAR(50) NOT NULL,
    AUTHOR          VARCHAR(200),
    CONTENT         VARCHAR(2500),
    RATE            NUMERIC(10, 2),
    CREATED_DATE    TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_DATE    TIMESTAMP DEFAULT NOW() NOT NULL,
    PRIMARY KEY (ID)
)