DROP TABLE IF EXISTS REVIEW_ENTRY CASCADE;

CREATE TABLE REVIEW_ENTRY
(
    ID              UUID NOT NULL,
    PRODUCT_ID      VARCHAR(50) NOT NULL,
    AUTHOR          VARCHAR(200),
    SUBJECT         VARCHAR(500),
    CONTENT         VARCHAR(2500),
    CREATED_DATE    TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_DATE    TIMESTAMP DEFAULT NOW() NOT NULL,
    PRIMARY KEY (ID)
)